version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: catalog-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  catalog-service:
    build: .
    container_name: catalog-service
    restart: always
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/catalogdb"
    ports:
      - "5000:5000"
    depends_on:
      - postgres



# Para apagar todo o banco existente do container. Faça isso apenas em ambiente de desenvolvimento ou protótipo.
# docker volume ls

#docker stop catalog-postgres
#docker rm catalog-postgres

# docker volume rm catalog-postgres-data

# docker-compose up -d

# docker run --name catalog-postgres -e POSTGRES_PASSWORD=123 -e POSTGRES_DB=catalog -p 5432:5432 -v ./init:/docker-entrypoint-initdb.d -d postgres
